title: scarf@127.0.0.1
description: making computer beep boop beep boop since 2020

author:
  name: scarf
  email: greenscarf005@gmail.com

contact:
  repo: "github.com/scarf005/scarf005.github.com"
  github: "github.com/scarf005"
  twitter: "twitter.com/scarf005"